export const MEDIA_UPDATE_SENT = "MEDIA_UPDATE_SENT";

export const ALBUM_EDIT_PUT = "ALBUM_EDIT_PUT";
export const ALBUM_DELETE = "ALBUM_DELETE";
export const ALBUM_MEDIA_GET = "ALBUM_MEDIA_GET";

export const ADMIN_GET_USERS = "ADMIN_GET_USERS";
export const ADMIN_GET_ROLES = "ADMIN_GET_ROLES";
export const ADMIN_GET_USER_DETAIL = "ADMIN_GET_USER_DETAIL";
export const ADMIN_UPDATE_USER_DETAILS = "ADMIN_UPDATE_USER_DETAILS";
export const ADMIN_UPDATE_USER_QUOTA = "ADMIN_UPDATE_USER_QUOTA";
export const ADMIN_GET_PENDING_PUBLIC_MEDIA_APPROVALS =
  "ADMIN_GET_PENDING_PUBLIC_MEDIA_APPROVALS";
export const ADMIN_APPROVE_PUBLIC_MEDIA = "ADMIN_APPROVE_PUBLIC_MEDIA";
export const ADMIN_DENY_PUBLIC_MEDIA = "ADMIN_DENY_PUBLIC_MEDIA";
export const ADMIN_GET_STATS = "ADMIN_GET_STATS";
