export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const RESET_PASSWORD_SENT = 'RESET_PASSWORD_SENT';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';


export const MEDIA_REQUEST = 'MEDIA_REQUEST';
export const USER_MEDIA_REQUEST = 'USER_MEDIA_REQUEST';
export const MEDIA_SUCCESS = 'MEDIA_SUCCESS';
export const MEDIA_FAILURE = 'MEDIA_FAILURE';
export const MEDIA_POST_SENT = 'MEDIA_POST_SENT';
export const MEDIA_POST_FAIL = 'MEDIA_POST_FAIL';
export const MEDIA_POST_SUCCESS = 'MEDIA_POST_SUCCESS';
export const MEDIA_DELETE_FAIL = 'MEDIA_DELETE_FAIL';
export const MEDIA_DELETE_DONE = 'MEDIA_DELETE_DONE';
export const MEDIA_UPDATE_SENT = 'MEDIA_UPDATE_SENT';
export const MEDIA_UPDATE_FAIL = 'MEDIA_UPDATE_FAIL';

export const ALBUM_REQUEST = 'ALBUM_REQUEST';
export const ALBUM_FAILURE = 'ALBUM_FAILURE';
export const ALBUM_EDIT_PUT = 'ALBUM_EDIT_PUT';

export const CONTACT_FORM_SENT = 'CONTACT_FORM_SENT';
export const CONTACT_FORM_FAIL = 'CONTACT_FORM_FAIL';