export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const RESET_PASSWORD_SENT = "RESET_PASSWORD_SENT";
export const NEW_PASSWORD_SENT = "NEW_PASSWORD_SENT";
export const UPDATE_USER_DETAILS_SENT = "UPDATE_USER_DETAILS_SENT";

export const MEDIA_REQUEST = "MEDIA_REQUEST";
export const MEDIA_FAILURE = "MEDIA_FAILURE";
export const MEDIA_POST_SENT = "MEDIA_POST_SENT";
export const MEDIA_POST_SUCCESS = "MEDIA_POST_SUCCESS";
export const MEDIA_DELETE_FAIL = "MEDIA_DELETE_FAIL";
export const MEDIA_DELETE_DONE = "MEDIA_DELETE_DONE";
export const MEDIA_UPDATE_SENT = "MEDIA_UPDATE_SENT";
export const MEDIA_RESET_MESSAGES = "MEDIA_RESET_MESSAGES";
export const SET_ACTIVE_MEDIA_MODAL = "SET_ACTIVE_MEDIA_MODAL";

export const ALBUM_REQUEST = "ALBUM_REQUEST";
export const ALBUM_FAILURE = "ALBUM_FAILURE";
export const ALBUM_EDIT_PUT = "ALBUM_EDIT_PUT";

export const CONTACT_FORM_SENT = "CONTACT_FORM_SENT";
export const CONTACT_FORM_FAIL = "CONTACT_FORM_FAIL";

export const SERVICES_TEAMSPEAK_GET_ACTIVE_LIST_SENT =
  "SERVICES_TEAMSPEAK_GET_ACTIVE_LIST_SENT";
export const SERVICES_TEAMSPEAK_GET_ACTIVE_LIST_FAIL =
  "SERVICES_TEAMSPEAK_GET_ACTIVE_LIST_FAIL";
export const SERVICES_DISCORD_GET_ACTIVE_LIST_SENT =
  "SERVICES_DISCORD_GET_ACTIVE_LIST_SENT";
export const SERVICES_DISCORD_GET_ACTIVE_LIST_FAIL =
  "SERVICES_DISCORD_GET_ACTIVE_LIST_FAIL";

export const USER_PROFILE_GET = "USER_PROFILE_GET";
export const USER_PROFILE_GET_FAIL = "USER_PROFILE_GET_FAIL";
export const USER_PROFILE_SERVICE_GET_UNREGISTERED_ACCOUNTS =
  "USER_PROFILE_SERVICE_GET_UNREGISTERED_ACCOUNTS";
export const USER_PROFILE_SERVICE_GET_UNREGISTERED_ACCOUNTS_FAIL =
  "USER_PROFILE_SERVICE_GET_UNREGISTERED_ACCOUNTS_FAIL";
export const USER_PROFILE_SERVICE_ADD_TS = "USER_PROFILE_SERVICE_ADD_TS";
export const USER_PROFILE_SERVICE_ADD_DISCORD =
  "USER_PROFILE_SERVICE_ADD_DISCORD";
export const USER_PROFILE_SERVICE_DELETE_TS = "USER_PROFILE_SERVICE_DELETE_TS";
export const USER_PROFILE_SERVICE_DELETE_DISCORD =
  "USER_PROFILE_SERVICE_DELETE_DISCORD";
export const USER_PROFILE_SERVICE_DELETE_FAIL =
  "USER_PROFILE_SERVICE_DELETE_FAIL";
export const USER_PROFILE_GET_API_TOKENS = "USER_PROFILE_GET_API_TOKENS";
export const USER_PROFILE_GET_API_TOKENS_FAIL =
  "USER_PROFILE_GET_API_TOKENS_FAIL";
export const USER_PROFILE_GENERATE_SHAREX_CONFIG =
  "USER_PROFILE_GENERATE_SHAREX_CONFIG";
export const USER_PROFILE_GENERATE_SHAREX_CONFIG_FAIL =
  "USER_PROFILE_GENERATE_SHAREX_CONFIG_FAIL";
export const USER_PROFILE_GENERATE_API_TOKEN =
  "USER_PROFILE_GENERATE_API_TOKEN";
export const USER_PROFILE_GENERATE_API_TOKEN_FAIL =
  "USER_PROFILE_GENERATE_API_TOKEN_FAIL";
export const USER_PROFILE_GET_STORAGE_QUOTA = "USER_PROFILE_GET_STORAGE_QUOTA";
export const USER_PROFILE_GET_STORAGE_QUOTA_FAIL =
  "USER_PROFILE_GET_STORAGE_QUOTA_FAIL";

export const ADMIN_GET_USERS = "ADMIN_GET_USERS";
export const ADMIN_GET_USERS_FAIL = "ADMIN_GET_USERS_FAIL";
export const ADMIN_GET_ROLES = "ADMIN_GET_ROLES";
export const ADMIN_GET_USER_DETAIL = "ADMIN_GET_USER_DETAIL";
export const ADMIN_GET_USER_DETAIL_FAIL = "ADMIN_GET_USER_DETAIL_FAIL";
export const ADMIN_UPDATE_USER_DETAILS = "ADMIN_UPDATE_USER_DETAILS";
export const ADMIN_UPDATE_USER_QUOTA = "ADMIN_UPDATE_USER_QUOTA";
export const ADMIN_GET_PENDING_PUBLIC_MEDIA_APPROVALS =
  "ADMIN_GET_PENDING_PUBLIC_MEDIA_APPROVALS";
export const ADMIN_APPROVE_PUBLIC_MEDIA = "ADMIN_APPROVE_PUBLIC_MEDIA";
export const ADMIN_DENY_PUBLIC_MEDIA = "ADMIN_DENY_PUBLIC_MEDIA";
